### PR TITLE
Set up website to grab and serve preseed

### PR DESCRIPTION
**Pull request by WillNilges**

### CODE REVIEW

**Review by asimonson1125 — APPROVED** [review]
I think you could have redirected the user to the URL rather than have the website save it and send its own copy since it's static but this works too. lgtm

**Review by MTFT-Games — APPROVED** [review]
Simple enough

**Comment by WillNilges** [comment]
@asimonson1125 Yeah, I was worried that that might confuse the preseed. I could change it to do that and then test it in dev...?

**Comment by MTFT-Games** [comment]
Ready to merge?

**Pull request merged**
